package org.pwss.view.screen;


import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Insets;
import java.util.Locale;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;

public class HomeScreen extends BaseScreen {
    private JPanel rootPanel;
    private JTabbedPane tabbedPane;
    private JPanel homeTab;
    private JPanel scanTab;
    private JPanel recentDiffsTab;
    private JButton quickScanButton;
    private JButton scanButton;
    private JTable diffTable;
    private JButton newDirectoryButton;
    private JTable recentScanTable;
    private JTable monitoredDirectoriesTable;
    private JProgressBar scanProgress;
    private JPanel scanProgressContainer;
    private JLabel scanProgressLabel;
    private JTextPane liveFeedText;
    private JLabel liveFeedTitle;
    private JScrollPane liveFeedContainer;
    private JLabel liveFeedDiffCount;
    private JPanel settingsTab;
    private JTextPane diffDetails;
    private JButton clearFeedButton;
    private JPanel filesTab;
    private JTable filesTable;
    private JTextField fileSearchField;
    private JCheckBox searchContainingCheckBox;
    private JCheckBox descendingCheckBox;
    private JTable fileSummaryTable;
    private JTextPane scanSummaryDetails;
    private JLabel searchResultCount;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    @Override
    protected String getScreenName() {
        return "Home";
    }

    @Override
    public JPanel getRootPanel() {
        return rootPanel;
    }

    public JButton getAddNewDirectoryButton() {
        return newDirectoryButton;
    }

    public JButton getScanButton() {
        return scanButton;
    }

    public JButton getQuickScanButton() {
        return quickScanButton;
    }

    public JTable getRecentScanTable() {
        return recentScanTable;
    }

    public JTable getMonitoredDirectoriesTable() {
        return monitoredDirectoriesTable;
    }

    public JTable getDiffTable() {
        return diffTable;
    }

    public JPanel getScanProgressContainer() {
        return scanProgressContainer;
    }

    public JScrollPane getLiveFeedContainer() {
        return liveFeedContainer;
    }

    public JTextPane getLiveFeedText() {
        return liveFeedText;
    }

    public JLabel getLiveFeedTitle() {
        return liveFeedTitle;
    }

    public JLabel getLiveFeedDiffCount() {
        return liveFeedDiffCount;
    }

    public JTabbedPane getTabbedPane() {
        return tabbedPane;
    }

    public JTextPane getDiffDetails() {
        return diffDetails;
    }

    public JButton getClearFeedButton() {
        return clearFeedButton;
    }

    public JTextField getFileSearchField() {
        return fileSearchField;
    }

    public JTable getFileScanSummaryTable() {
        return fileSummaryTable;
    }

    public JCheckBox getDescendingCheckBox() {
        return descendingCheckBox;
    }

    public JTable getFilesTable() {
        return filesTable;
    }

    public JCheckBox getSearchContainingCheckBox() {
        return searchContainingCheckBox;
    }

    public JTextPane getScanSummaryDetails() {
        return scanSummaryDetails;
    }

    public JLabel getSearchResultCount() {
        return searchResultCount;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane = new JTabbedPane();
        tabbedPane.setTabPlacement(1);
        tabbedPane.setToolTipText("");
        rootPanel.add(tabbedPane, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        homeTab = new JPanel();
        homeTab.setLayout(new GridLayoutManager(3, 1, new Insets(10, 10, 10, 10), -1, -1));
        tabbedPane.addTab("\uD83C\uDFE0 Home", homeTab);
        quickScanButton = new JButton();
        quickScanButton.setText("Quick scan");
        homeTab.add(quickScanButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$(null, Font.BOLD, 16, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setText("Most recent scans");
        homeTab.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        homeTab.add(scrollPane1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        recentScanTable = new JTable();
        recentScanTable.setAutoResizeMode(2);
        recentScanTable.setShowHorizontalLines(true);
        scrollPane1.setViewportView(recentScanTable);
        scanTab = new JPanel();
        scanTab.setLayout(new GridLayoutManager(10, 4, new Insets(10, 10, 10, 10), -1, -1));
        tabbedPane.addTab("\uD83D\uDD0E Scan", scanTab);
        final JLabel label2 = new JLabel();
        Font label2Font = this.$$$getFont$$$(null, Font.BOLD, 16, label2.getFont());
        if (label2Font != null) label2.setFont(label2Font);
        label2.setHorizontalAlignment(0);
        label2.setText("Monitored directories");
        scanTab.add(label2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane2 = new JScrollPane();
        scanTab.add(scrollPane2, new GridConstraints(1, 0, 5, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        monitoredDirectoriesTable = new JTable();
        monitoredDirectoriesTable.setAutoResizeMode(2);
        scrollPane2.setViewportView(monitoredDirectoriesTable);
        liveFeedContainer = new JScrollPane();
        scanTab.add(liveFeedContainer, new GridConstraints(1, 1, 8, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(450, -1), new Dimension(450, -1), null, 0, false));
        liveFeedText = new JTextPane();
        liveFeedText.setEditable(false);
        liveFeedText.setText("");
        liveFeedContainer.setViewportView(liveFeedText);
        liveFeedTitle = new JLabel();
        Font liveFeedTitleFont = this.$$$getFont$$$(null, Font.BOLD, 16, liveFeedTitle.getFont());
        if (liveFeedTitleFont != null) liveFeedTitle.setFont(liveFeedTitleFont);
        liveFeedTitle.setHorizontalAlignment(0);
        liveFeedTitle.setText("Scan logs");
        scanTab.add(liveFeedTitle, new GridConstraints(0, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        scanTab.add(panel1, new GridConstraints(7, 0, 3, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        newDirectoryButton = new JButton();
        newDirectoryButton.setText("New directory");
        panel1.add(newDirectoryButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        liveFeedDiffCount = new JLabel();
        liveFeedDiffCount.setText("");
        scanTab.add(liveFeedDiffCount, new GridConstraints(9, 2, 1, 2, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        scanButton = new JButton();
        scanButton.setText("Full scan");
        scanTab.add(scanButton, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        clearFeedButton = new JButton();
        clearFeedButton.setText("Clear feed");
        scanTab.add(clearFeedButton, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        filesTab = new JPanel();
        filesTab.setLayout(new GridLayoutManager(2, 1, new Insets(10, 10, 10, 10), -1, -1));
        tabbedPane.addTab("\uD83D\uDDC4\uFE0F Files", filesTab);
        final JSplitPane splitPane1 = new JSplitPane();
        filesTab.add(splitPane1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        final JScrollPane scrollPane3 = new JScrollPane();
        splitPane1.setLeftComponent(scrollPane3);
        filesTable = new JTable();
        scrollPane3.setViewportView(filesTable);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        splitPane1.setRightComponent(panel2);
        final JSplitPane splitPane2 = new JSplitPane();
        splitPane2.setOrientation(0);
        panel2.add(splitPane2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        final JScrollPane scrollPane4 = new JScrollPane();
        splitPane2.setLeftComponent(scrollPane4);
        fileSummaryTable = new JTable();
        scrollPane4.setViewportView(fileSummaryTable);
        final JScrollPane scrollPane5 = new JScrollPane();
        splitPane2.setRightComponent(scrollPane5);
        scanSummaryDetails = new JTextPane();
        scanSummaryDetails.setEditable(false);
        scrollPane5.setViewportView(scanSummaryDetails);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(5, 2, new Insets(0, 0, 0, 0), -1, -1));
        filesTab.add(panel3, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, true));
        fileSearchField = new JTextField();
        panel3.add(fileSearchField, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Search for file");
        panel3.add(label3, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        searchContainingCheckBox = new JCheckBox();
        searchContainingCheckBox.setText("File name contains");
        panel3.add(searchContainingCheckBox, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        descendingCheckBox = new JCheckBox();
        descendingCheckBox.setText("Descending");
        panel3.add(descendingCheckBox, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        searchResultCount = new JLabel();
        searchResultCount.setText("");
        panel3.add(searchResultCount, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        recentDiffsTab = new JPanel();
        recentDiffsTab.setLayout(new GridLayoutManager(2, 1, new Insets(10, 10, 10, 10), -1, -1));
        tabbedPane.addTab("⚠\uFE0F Recent diffs", recentDiffsTab);
        final JSplitPane splitPane3 = new JSplitPane();
        recentDiffsTab.add(splitPane3, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        final JScrollPane scrollPane6 = new JScrollPane();
        splitPane3.setLeftComponent(scrollPane6);
        diffTable = new JTable();
        diffTable.setAutoResizeMode(4);
        diffTable.setFillsViewportHeight(true);
        scrollPane6.setViewportView(diffTable);
        final JScrollPane scrollPane7 = new JScrollPane();
        splitPane3.setRightComponent(scrollPane7);
        diffDetails = new JTextPane();
        scrollPane7.setViewportView(diffDetails);
        final JLabel label4 = new JLabel();
        Font label4Font = this.$$$getFont$$$(null, Font.BOLD, 16, label4.getFont());
        if (label4Font != null) label4.setFont(label4Font);
        label4.setText("Most recently detected diffs");
        recentDiffsTab.add(label4, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        settingsTab = new JPanel();
        settingsTab.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane.addTab("⚙\uFE0F Settings", settingsTab);
        scanProgressContainer = new JPanel();
        scanProgressContainer.setLayout(new GridLayoutManager(1, 2, new Insets(10, 10, 10, 10), -1, -1));
        rootPanel.add(scanProgressContainer, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, true));
        scanProgress = new JProgressBar();
        scanProgress.setIndeterminate(true);
        scanProgressContainer.add(scanProgress, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        scanProgressLabel = new JLabel();
        scanProgressLabel.setText("Scan in progress");
        scanProgressContainer.add(scanProgressLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

}
