package org.pwss.view.screen;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import java.awt.Dimension;
import java.awt.Insets;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextPane;

/**
 * Screen class that represents the details of a scan, providing UI components
 * to display and interact with scan
 * data.
 */
public class ScanDetailsScreen extends BaseScreen {
    /**
     * Button to navigate back from this screen.
     */
    private JButton backButton;
    /**
     * Table to display scan summary information.
     */
    private JTable scanSummaryTable;
    /**
     * Root panel that contains all UI components of this screen.
     */
    private JPanel rootPanel;
    /**
     * Table to display differences (diffs) between scans.
     */
    private JTable diffTable;
    /**
     * Text pane to show detailed information about a selected scan summary.
     */
    private JTextPane scanSummaryDetails;
    /**
     * Text pane to show details of the differences (diffs) between scans.
     */
    private JTextPane diffDetails;

    {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    @Override
    public String getScreenName() {
        return "Scan Details";
    }

    /**
     * Returns the back button component.
     *
     * @return The JButton instance used for navigating back
     */
    public JButton getBackButton() {
        return backButton;
    }

    /**
     * Returns the scan summary table component.
     *
     * @return The JTable instance displaying scan summaries
     */
    public JTable getScanSummaryTable() {
        return scanSummaryTable;
    }

    /**
     * Returns the root panel of this screen which contains all UI components.
     *
     * @return The JPanel instance representing the root panel
     */
    @Override
    public JPanel getRootPanel() {
        return rootPanel;
    }

    /**
     * Returns the differences (diffs) table component.
     *
     * @return The JTable instance displaying scan diffs
     */
    public JTable getDiffTable() {
        return diffTable;
    }

    /**
     * Returns the text pane used to display details of differences (diffs) between
     * scans.
     *
     * @return The JTextPane instance showing diff details
     */
    public JTextPane getDiffDetails() {
        return diffDetails;
    }

    /**
     * Returns the text pane used to display details about a selected scan summary.
     *
     * @return The JTextPane instance showing scan summary details
     */
    public JTextPane getScanSummaryDetails() {
        return scanSummaryDetails;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JTabbedPane tabbedPane1 = new JTabbedPane();
        rootPanel.add(tabbedPane1,
                new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null,
                        0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(10, 10, 10, 10), -1, -1));
        tabbedPane1.addTab("\uD83D\uDCCB Summaries", null, panel1, "Here you can see file summaries");
        final JSplitPane splitPane1 = new JSplitPane();
        panel1.add(splitPane1,
                new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null,
                        new Dimension(200, 200), null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        splitPane1.setLeftComponent(scrollPane1);
        scanSummaryTable = new JTable();
        scrollPane1.setViewportView(scanSummaryTable);
        final JScrollPane scrollPane2 = new JScrollPane();
        splitPane1.setRightComponent(scrollPane2);
        scanSummaryDetails = new JTextPane();
        scanSummaryDetails.setEditable(false);
        scrollPane2.setViewportView(scanSummaryDetails);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 1, new Insets(10, 10, 10, 10), -1, -1));
        tabbedPane1.addTab("⚠\uFE0F Diffs detected", null, panel2, "Here you can see the diffs detected for the scan");
        final JSplitPane splitPane2 = new JSplitPane();
        panel2.add(splitPane2,
                new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null,
                        new Dimension(200, 200), null, 0, false));
        final JScrollPane scrollPane3 = new JScrollPane();
        splitPane2.setLeftComponent(scrollPane3);
        diffTable = new JTable();
        scrollPane3.setViewportView(diffTable);
        final JScrollPane scrollPane4 = new JScrollPane();
        splitPane2.setRightComponent(scrollPane4);
        diffDetails = new JTextPane();
        diffDetails.setEditable(false);
        scrollPane4.setViewportView(diffDetails);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(1, 1, new Insets(0, 10, 10, 10), -1, -1));
        rootPanel.add(panel3,
                new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null,
                        0, true));
        backButton = new JButton();
        backButton.setText("Back");
        panel3.add(backButton,
                new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                        GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

}
